### ISSUE TITLE
Ethische Frage/n?

### ISSUE THREAD

**Issue by ratnim** [ratnim/SelfawareMonopoly#1]
Welche Frage bzw. Fragen wollen wir beantworten?

**Comment by ratnim** [comment]
Eröffnet doch pro Frage einen Issue mit dem Tag "Ethische Frage" dann kann man die Frage spezifischen Diskussionen dort führen.

**Comment by paszin** [comment]
Übersicht zu allen ethischen Fragen: https://github.com/ratnim/SelfawareMonopoly/labels/ethical%20question
