### ISSUE TITLE
Client-Server QT Implementation

### ISSUE THREAD

**Issue by ratnim** [ratnim/SelfawareMonopoly#10]
Implement the Project in C++ using a client-server architecture.

## Server
The server will be implemented using C++ and Qt. It serves as a state machine and listens to HTTP requests to modify or query the state. The requests are following the REST model and the interchange data format is json. This is a console application that implements the rules of the game.

## Client
The client will be implemented in C++ and Qt. At startup the user must enter a server ip in order to play a game. After that it queries constantly the current state from the server. The state is then visualized using OpenGL or the Qt software renderer. On the users turn the client visualizes the actions it can take. Taking a action results in a query that is sent to the server to modify its state.

## Data transfer
Using plain text REST as a transfer standard allows to easily debug the connection. The advantage of keeping the connection asynchon is that it simplifies its implementation because of the abstraction from low level data transfers. In contrast it is not the most efficient way of transporting data.

### Coding Style
The most up to date version of the C++ language that is aviable on all mayor platforms should be used. The used compilers should include Visual Studio 2017 15.6 and clang5 and the program should work on Windows and Linux using CMake. Every change must be commited on a seperate branch which will be reviewed by multiple people when merging into the master.

### Why QT?
It contains platform independent abstractions for network, filesystem, databases, user interface and opengl.

**Comment by paszin** [comment]
I am not familiar with C++ and Qt but "After that it queries constantly the current state from the server." sounds like a use case for web sockets.

**Comment by Highlife1911** [comment]
outdated; server is okay but client is done via js.
