### ISSUE TITLE
Build Houses/Hotels

### ISSUE THREAD

**Issue by ratnim** [ratnim/SelfawareMonopoly#102]
Enable build when having a full set of streets.
API:
- [x] build houses

Logic:
- [x] build while idle state

**Comment by ratnim** [comment]
Possible Request:
```
{
     "request" :  "construct_building" 
}
```
Request:
```
{
     "request" : "construct_building",
      "data": { <index>: <level>, <index>: <level>, <index>: level} 
}
```

Requirements:
- [ ] Levels can only differ by 1
- [ ] Entire group needs to be owned

**Comment by Tobias1595** [comment]
Could you please explain the syntax of the request data?
