### ISSUE TITLE
Technology Stack

### ISSUE THREAD

**Issue by ratnim** [ratnim/SelfawareMonopoly#13]
Folgend aus #3,  #7 und #8 . Welche Technologien wollen wir benutzen.

**Comment by paszin** [comment]
Ich würde einfach mal neben C++ mit Qt #10  noch Javascript mit three.js ins Rennen werfen. Vorteile wären einfaches Deployment und für jeden im Browser spielbar.

**Comment by paszin** [comment]
Client: Javascript Website 2D, mit Websocket Connection

**Comment by ratnim** [comment]
Server: C++
Alternative 1:
QT, SQLite
Alternative 2:
Websocketpp, JSON?, SQLite
Alternative 3: 
Boost, SQLite

**Comment by Highlife1911** [comment]
SQLite is already integrated into QT.

**Comment by ratnim** [comment]
Server:  cpp
Client: js

**Comment by ratnim** [comment]
- [ ] #20
