### ISSUE TITLE
InvalidRequest: Session is not valid. 

### ISSUE THREAD

**Issue by paszin** [ratnim/SelfawareMonopoly#134]
ans backend team: was bedeutet die fehlermeldung?

Setup: Dockerimage basierend auf 0f2b9a3dcf (feature/websocket_server)
Szenario: Cache ist geleert, neuer Spieler angelegt, join game, verbunden mit game websocket. und dann bekomme ich vom websocket `InvalidRequest: Session is not valid. `

Ist der Fehler bekannt? oder in einem anderen Branch behoben? Und was ist die semantische Bedeutung?

**Comment by ratnim** [comment]
Noch nicht bekannt. Ist das auf dem master?

**Comment by ratnim** [comment]
Also auf dem Branch https://github.com/ratnim/SelfawareMonopoly/tree/feature/dockerize_ci kann ich das Spiel normal joinen und starten. Beim Würfeln gibt es aber Unstimmigkeiten. Ich werde mal dem Server print statements hinzufügen um zu sehen was passiert.

**Comment by ratnim** [comment]
Debug Prints sind drin. Es scheint so als ob der Feheler auf dem gennanten Branch nicht besteht.

**Comment by ratnim** [comment]
#126 solves this issue on the master.
