### ISSUE TITLE
Repository Rights

### ISSUE THREAD

**Issue by Highlife1911** [ratnim/SelfawareMonopoly#14]
Can you increase our developer rights in this repository?

**Comment by ratnim** [comment]
Unfortunately, there are just two levels of permission. Owner and Collaborator. https://help.github.com/articles/permission-levels-for-a-user-account-repository/
Is there anything you can't do?

**Comment by Highlife1911** [comment]
I don't have a settings tab and can't register services like travis or appveyor.

**Comment by ratnim** [comment]
Ok, never did this bevor on GitHub. Do you need a fast solution or can we solve the problem together on Tuesday?

**Comment by Highlife1911** [comment]
In the settings tab there should be an option to change use rights. For me it should state Read/Write/Admin. To set up travis, admin is required.

This is not an urgent issue.
