### ISSUE TITLE
Server-Client Kommunikation

### ISSUE THREAD

**Issue by MarieTheresThomas** [ratnim/SelfawareMonopoly#22]
Szenario:
- 1 Server, 2 Browser die miteinander interagieren sollen
- Sever: C++, Client: JS
- spiel soll rundenbasiert ablaufen, in jeder Runde soll der Spieler nach Würfelwurf gefragt werden
#20

**Comment by MarieTheresThomas** [comment]
belongs to #20 Technical prototypes

**Comment by Highlife1911** [comment]
The server template is located in https://github.com/ratnim/SelfawareMonopoly/tree/feature/gamingloop

**Comment by Highlife1911** [comment]
Also think about using ssl for data exchange.
