### ISSUE TITLE
API-Instagram

### ISSUE THREAD

**Issue by MarieTheresThomas** [ratnim/SelfawareMonopoly#28]
- request twitter Profile ( https://www.facebook.com/username)
- search friends' list
- take actions from user profile (Login needed): Like, Post

**Comment by paszin** [comment]
What the API provides

* GET User information (name, follower count, profile picture etc.)
* GET Recent Posts 

https://www.instagram.com/developer/endpoints/users/

**Comment by paszin** [comment]
Hierzu ist alles notiert.
