### ISSUE TITLE
Game Design

### ISSUE THREAD

**Issue by ratnim** [ratnim/SelfawareMonopoly#3]
Welches Spiel eignet sich für unser Szenario/ ethische Frage?

**Comment by ratnim** [comment]
Bis jetzt hatten wir uns auf Monopoly geeinigt, bleibt es dabei oder jemand noch Einwände oder bessere Vorschläge?

**Comment by Highlife1911** [comment]
Mann kann die Monopoly-Version personalisieren. Also je nach Ort des Spielers werden die Straßennamen angepasst.
Alternativ kann man auch verschiedene Versionen mithilfe von lokalisierung (QObject::tr) implementieren.

**Comment by paszin** [comment]
ein bisschen ähnlich: **Risiko**

**Comment by ratnim** [comment]
Wir bleiben bei Monoply.
