### ISSUE TITLE
Game_Database

### ISSUE THREAD

**Issue by MarieTheresThomas** [ratnim/SelfawareMonopoly#31]
- transfer results from API calls into database
- common interface for all results of API calls
- Highscore

**Comment by paszin** [comment]
irgendwie les ich überall SQLite, aber wäre es nicht praktischer sowas wie mongoDB oder firebase DB zu nutzen, wo man einfach json reinschreiben kann. (https://firebase.google.com/docs/database/cpp/start)

**Comment by Highlife1911** [comment]
SQLite hat den Vorteil, dass man nicht einen extra Datenbankserver mitlaufen lassen muss. Außerdem ist es in Qt bereits integriert und erzeugt keine zusätzliche Abhängigkeit. Wir wissen aktuell noch nicht, ob wirklich all unsere Daten jsons sind oder ob wir auch reguläre spaltenbasierte Daten haben.

Unser Projektfokus liegt auch eher in der beschaffung der Daten und nicht in der Anwendung. Daher ist der Vorteil, dass man auf Datenbankebene jsons verarbeiten kann zweitrangig.

**Comment by Highlife1911** [comment]
Ein minimales Beispiel befindet sich jetzt auf dem feature/gameloop branch.
