### ISSUE TITLE
Geschichte Monopoly

### ISSUE THREAD

**Issue by ratnim** [ratnim/SelfawareMonopoly#4]
Wie am Dienstag angemerkt, wäre es schön noch mal herauszufinden, wofür Monopoly eigentlich gedacht war. Und ob das für uns nutzbar ist.

**Comment by paszin** [comment]
> Ein paar Jahre (etwa 1930 Anm. v. mir) später schlägt Charles B. Darrow - infolge des Börsencrashs und der Weltwirtschaftskrise arbeitslos - dem Unternehmen Parker vor, seine Spielkreation "Monopoly" zu kaufen und zu vertreiben.

> Das Spiel trifft den Nerv der Zeit: Krisenverlierer können sich durch das Spiel in eine andere Welt flüchten, astronomische Gewinne genießen und sich der Illusion vom großen Geld hingeben.


[Quelle](http://www.spiegel.de/wirtschaft/jura-kurios-wem-gehoert-eigentlich-monopoly-a-725144-6.html)
