### ISSUE TITLE
Forumsbeitrag "Gruppen Beschreibung"

### ISSUE THREAD

**Issue by ratnim** [ratnim/SelfawareMonopoly#5]
Im Forum: https://moodle.hpi3d.de/mod/forum/discuss.php?d=1551 soll eine kurze Beschreibung unserer Gruppe gepostet werde.

**Comment by ratnim** [comment]
Namen aller Gruppenmitglieder
(vorläufiger) Arbeitstitel des Prototypen
Nennung der Technik(en) bzw. der Programmverhalten, mit der/denen ihr euch beschäftigen möchtet
Kurzbeschreibung eines Szenarios, in dem eine produktifizierte Variante eurers geplanten Prototypen eingesetzt werden könnte (Worst-Case Scenario)

**Comment by paszin** [comment]
Programmbeschreibung:

Das klassische Monopoly ergänzt um eine "Selfaware" Komponente. Diese Komponente schlägt den Spielern Deals vor, wie neu würfeln oder andere vorteilhafte Aktionen. Im Gegenzug gibt der Spieler Spielanteile ab, wie z.B. anteilige Einnahmen. Um diese Anteile zurückzugewinnen, kann der Spieler Informationen über sich Preis geben, wie z.B. Facebook Account.
