### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by MarieTheresThomas** [ratnim/SelfawareMonopoly#50]
- #51 Persistierung der States
- #53 Kommunikation Client-Server

- #54 HTTPS Implementierung

**Comment by Highlife1911** [comment]
- [ ] Fileserver
- [ ] Fileserver - dynamic routing
- [ ] Fileserver - tests
- [ ] WebsocketServer - accept only
- [ ] WebsocketServer - routes
- [ ] WebsocketServer - tests
- [ ] Gamelogic
- [ ] Certificate that is ready for at least TLS 1.0 and usable by Qt
- [ ] Multithreaded `accept`

**Comment by paszin** [comment]
Könnt ihr bitte eine Readme in dem server verzeichnis anlegen für alle nicht c++-ler.
Einfach nur einmal alle befehle, die man eingeben muss um den server zu starten

**Comment by Highlife1911** [comment]
Bis jetzt ist im Server nur die Overview Seite fertig. Am rest sitzt gerade Tobias.

1. Branch feature/websocket_server mit submodulen clonen
2. Visual Studio 2017 installieren
3. Qt5.10 installieren 

Windows:
Im Verzeichnis server/buildscripts gibt es eine configure.bat.in. Diese kann man umbenennen zu einer configure.bat. Anschließend kann man darin den Qt-Pfad anpassen. Dann kann man das Projekt mithilfe der build.bat erstellen und mit der open.bat öffnen. Aus Visual Studio kann man den server dannach starten.

Mit Linux sollte cmake out of the box funktionieren. Am Freitag werde ich mich an CI mit Travis setzen und den cppServer auf meiner Hardware laufen lassen. 

Auf MacOS have ich keine ahnung.

**Comment by ratnim** [comment]
https://github.com/ratnim/SelfawareMonopoly/pull/57
