### ISSUE TITLE
Gesellschaftsbezug

### ISSUE THREAD

**Issue by ratnim** [ratnim/SelfawareMonopoly#6]
Wo könnte ein solches System genutzt werde. 
Wird oder wurde ein solches System schon genutzt? 
Es muss nicht digital sein.

**Comment by ratnim** [comment]
Fällt der Ablasshandel der Katholischen Kirche in diese Kategorie?

**Comment by ratnim** [comment]
Steueroasen für Großkonzerne?

**Comment by paszin** [comment]
ganz allgemein Korruption und auch Wettbetrug.

z.B. gekaufte Abstimmungsergebnisse (:= geänderte Würfelzahl)
