### ISSUE TITLE
Entwürfe Asset Stil

### ISSUE THREAD

**Issue by ratnim** [ratnim/SelfawareMonopoly#73]
Stile:
perspektivische Ansicht

- [ ] Low Poly Art/Aggressive Farben
- [ ] In A Nutshell  
- [ ] doodling
- [ ] realistic/photo realistic
- [ ] original board game 

Ideen:

- Häuser unterschiedlich (Holzhütte bis Schloss)

Spielfiguren:

- [ ] Humanoide Figur
- [ ] Old School Monopoly
- [ ] Avatare
- [ ] Karikaturen

**Comment by ratnim** [comment]
Erste Entwürfe mit @fuxart besprochen. Weiter folgen.

**Comment by fuxart** [comment]
Zwischenstand am 27.07., erste fertige Entwürfe am 03.08.
