### ISSUE TITLE
Spielszenario

### ISSUE THREAD

**Issue by ratnim** [ratnim/SelfawareMonopoly#8]
Auf Geräte Ebene:

Wo und wie soll gespielt werden (Handy, Browser, Desktop, Jeder ein eigenes Geräte etc...)? 
Wie wird die "Selfaware Komponente" durch den Spieler genutzt?

**Comment by ratnim** [comment]
Ich fande die Idee ganz nett, alle spielen an einem Rechner und man bekommt per Handy Zugriff auf die Selfaware Komponente.

**Comment by Highlife1911** [comment]
Gefällt mir garnicht, da das mich und Tobias sehr behindern würde.

**Comment by ratnim** [comment]
@Highlife1911 die Alternative mir einfallen wären
- jeder spielt am eigenen Client
- alle spielen an einem Client(Wie kann man dann geheime Aktionen machen?) -> eher keine Alternative

**Comment by paszin** [comment]
Für das "Schummeln" finde ich es wichtig, dass andere es nicht mitbekommen. Wenn alle an einem Monitor spielen, bekommt man nachwievor mit, wenn jemand am Handy gerade Einfluss nimmt. (Auch wenn das Spiel so bestimmt etwas geselliger wird)

Deswegen tendiere ich auch zu jeder verfolgt das Spiel auf seinem Gerät.

**Comment by MarieTheresThomas** [comment]
• Räumliche Anwesenheit der Spieler nicht relevant
    • Transparent für alle Spieler
        ◦ Spielerinfos
            ▪ Besitz von Strassen
            ▪ Besitz von Geld
            ▪ Ausführen eines Spielzuges
            ▪ Ziehen einer Ereigniskarte
        ◦ Intransparent für alle anderen Spieler
            ▪ Interaktion eines Spielers mit Selfaware-Komponente
            ▪ Status Quo der Selfaware-Komponente
    • Konsistenz des Geldsystems
        ◦ Geldbesitz jedes Spielers ist für alle anderen Spieler transparent, Visualisierung durch Scheine
        ◦ Geld kann nicht "aus dem Nichts" an einen Spieler vergeben/entzogen werden 
        ◦ System kann dem Spieler Geld durch ereigniskarten/manipulierte Spielzüge der anderen Spieler zuführen/abführen/umverteilen
    • Proaktives System
        ◦ Interaktion des Spielers mit System ist nicht zeitlich an den eigenen Spielzug gebunden
        ◦ permanete Möglichkeit der Informationspreisgabe

**Comment by ratnim** [comment]
Restful Interface am Server.
Clients senden anfragen, und erhalten den Spielstand.
