### ISSUE TITLE
Hide unusable buttons

### ISSUE THREAD

**Issue by Zanthelo** [ratnim/SelfawareMonopoly#83]
Currently every button is shown and clickable regardless of whether it is possible to use the button or not. If one clicks a button which is not usable at the moment we receive an error from the server.
Example: It is not my turn, but I click the roll dice button.
The buttons which are unusable should be hidden / grayed out.

**Comment by Highlife1911** [comment]
There are a lot of buttons in a future version, so you should hide the buttons.
