### ISSUE TITLE
Language in this Repository

### ISSUE THREAD

**Issue by Highlife1911** [ratnim/SelfawareMonopoly#9]
Keep this repository in German or English? I would prefer English a a development language and keep the game in German.

**Comment by ratnim** [comment]
Thought about make the Conception in german, because its easier to understand.

**Comment by paszin** [comment]
Also ich bin für Englisch :wink:

**Comment by ratnim** [comment]
Then let's stick to English.

**Comment by paszin** [comment]
verdammt, das mit der Ironie hat nicht geklappt

**Comment by ratnim** [comment]
Die Konzeption wird in  deutsch erfolgen. Code und tissues die den Code betreffen werden in English sein.
